const level1 = new Level(
    [
        new Chicken_Normal(),
        new Chicken_Normal(),
        new Chicken_Normal(),
        new Chicken_Normal(),
        new Chicken_Normal(),
        new Chicken_Normal(),
        new Chicken_Small(),
        new Chicken_Small(),
        new Chicken_Small(),
        new Chicken_Small(),
        new Chicken_Small(),
        new Chicken_Small(),
    ],

    [
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
    ],

    [
        new BackgroundObjekt('./assets/img/5_background/layers/air.png', -719),
        new BackgroundObjekt('./assets/img/5_background/layers/3_third_layer/2.png', -719),
        new BackgroundObjekt('./assets/img/5_background/layers/2_second_layer/2.png', -719),
        new BackgroundObjekt('./assets/img/5_background/layers/1_first_layer/2.png', -719),
        new BackgroundObjekt('./assets/img/5_background/layers/air.png', 0),
        new BackgroundObjekt('./assets/img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObjekt('./assets/img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObjekt('./assets/img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObjekt('./assets/img/5_background/layers/air.png', 719),
        new BackgroundObjekt('./assets/img/5_background/layers/3_third_layer/2.png', 719),
        new BackgroundObjekt('./assets/img/5_background/layers/2_second_layer/2.png', 719),
        new BackgroundObjekt('./assets/img/5_background/layers/1_first_layer/2.png', 719),
        new BackgroundObjekt('./assets/img/5_background/layers/air.png', 1438),
        new BackgroundObjekt('./assets/img/5_background/layers/3_third_layer/1.png', 1438),
        new BackgroundObjekt('./assets/img/5_background/layers/2_second_layer/1.png', 1438),
        new BackgroundObjekt('./assets/img/5_background/layers/1_first_layer/1.png', 1438),
        new BackgroundObjekt('./assets/img/5_background/layers/air.png', 2157),
        new BackgroundObjekt('./assets/img/5_background/layers/3_third_layer/2.png', 2157),
        new BackgroundObjekt('./assets/img/5_background/layers/2_second_layer/2.png', 2157),
        new BackgroundObjekt('./assets/img/5_background/layers/1_first_layer/2.png', 2157),
        new BackgroundObjekt('./assets/img/5_background/layers/air.png', 2876),
        new BackgroundObjekt('./assets/img/5_background/layers/3_third_layer/1.png', 2876),
        new BackgroundObjekt('./assets/img/5_background/layers/2_second_layer/1.png', 2876),
        new BackgroundObjekt('./assets/img/5_background/layers/1_first_layer/1.png', 2876),
    ],
);